// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Scott Key

// Command export-search builds a D1-compatible SQL file for the bardbase
// search database. It reads from the full bardbase.db and writes a stripped,
// denormalized SQL file containing only FTS5 virtual tables needed for search.
//
// Tables produced:
//
//   - text_fts      content+char_name indexed, metadata columns UNINDEXED
//   - lexicon_fts   key+orthography+full_text indexed
//   - reference_fts headword+raw_text indexed
//
// All tables use the trigram tokenizer (D1-compatible). Metadata needed for
// search result display is stored as UNINDEXED columns to avoid joins at
// query time. Data is inserted in batched transactions to stay within D1's
// per-query timeout.
//
// Usage:
//
//	go run ./cmd/export-search
//	go run ./cmd/export-search -src ../../build/bardbase.db -out ../../build/bardbase-search.sql
package main

import (
	"bufio"
	"database/sql"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/scottdkey/bardbase/projects/capell/internal/constants"
	"github.com/scottdkey/bardbase/projects/capell/internal/parser"
	_ "modernc.org/sqlite"
)


func main() {
	srcPath := flag.String("src", "../../build/bardbase.db", "Source database path")
	outPath := flag.String("out", "../../build/bardbase-search.sql", "Output SQL file path")
	flag.Parse()

	if _, err := os.Stat(*srcPath); err != nil {
		log.Fatalf("source database not found: %s", *srcPath)
	}

	src, err := openReadOnly(*srcPath)
	if err != nil {
		log.Fatalf("open source db: %v", err)
	}
	defer src.Close()

	f, err := os.Create(*outPath)
	if err != nil {
		log.Fatalf("create output file: %v", err)
	}
	defer f.Close()

	w := bufio.NewWriterSize(f, 4*1024*1024)

	log.Printf("exporting search database to %s", *outPath)

	writeHeader(w)
	writeSchema(w)
	if err := writeTextFTS(w, src); err != nil {
		log.Fatalf("text_fts: %v", err)
	}
	if err := writeLexiconFTS(w, src); err != nil {
		log.Fatalf("lexicon_fts: %v", err)
	}
	if err := writeReferenceFTS(w, src); err != nil {
		log.Fatalf("reference_fts: %v", err)
	}
	if err := writeReferenceSpans(w, src); err != nil {
		log.Fatalf("reference_spans: %v", err)
	}
	if err := writeLexiconDrawer(w, src); err != nil {
		log.Fatalf("lexicon_drawer: %v", err)
	}

	if err := w.Flush(); err != nil {
		log.Fatalf("flush: %v", err)
	}

	info, _ := f.Stat()
	log.Printf("done — %.1f MB written to %s", float64(info.Size())/1024/1024, *outPath)
}

func writeHeader(w *bufio.Writer) {
	fmt.Fprint(w, `-- bardbase-search.sql
-- Generated by cmd/export-search. Import with:
--   wrangler d1 execute <db-name> --remote --file bardbase-search.sql
--
-- All tables use FTS5 with the trigram tokenizer (D1-compatible).
-- UNINDEXED columns store metadata for result display without being searchable.
-- Data is inserted in batched transactions to stay within D1's per-query limits.

PRAGMA foreign_keys=OFF;

`)
}

func writeSchema(w *bufio.Writer) {
	fmt.Fprint(w, `DROP TABLE IF EXISTS text_fts;
DROP TABLE IF EXISTS lexicon_fts;
DROP TABLE IF EXISTS reference_fts;
DROP TABLE IF EXISTS reference_spans;
DROP TABLE IF EXISTS lexicon_drawer;

-- text_fts: full-text search over all play/poem lines across all editions.
CREATE VIRTUAL TABLE text_fts USING fts5(
  content,
  char_name,
  work_title,
  work_slug,
  edition_code,
  act,
  scene,
  line_number,
  tokenize='trigram'
);

-- lexicon_fts: Schmidt Shakespeare Lexicon (~20K entries).
CREATE VIRTUAL TABLE lexicon_fts USING fts5(
  key,
  orthography,
  full_text,
  letter,
  tokenize='trigram'
);

-- reference_fts: Onions, Abbott, Bartlett, Henley-Farmer glossaries (~97K entries).
CREATE VIRTUAL TABLE reference_fts USING fts5(
  headword,
  raw_text,
  source_code,
  source_name,
  tokenize='trigram'
);

-- reference_spans: pre-computed citation byte-range spans and structured citation list.
-- Keyed by reference_entry id. Queried at runtime by the /api/reference/entry/[id] route.
CREATE TABLE reference_spans (
  id INTEGER PRIMARY KEY,
  citation_spans TEXT NOT NULL,
  citations TEXT NOT NULL
);

-- lexicon_drawer: stripped lexicon entry JSON for the inline reference drawer.
-- Omits full citation text/matched-line data (those live on the prerendered entry page).
-- One row per lexicon_entry id; entries sharing a base_key get the same JSON payload.
CREATE TABLE lexicon_drawer (
  id INTEGER PRIMARY KEY,
  data TEXT NOT NULL
);

`)
}

func writeTextFTS(w *bufio.Writer, src *sql.DB) error {
	rows, err := src.Query(`
		SELECT tl.id, tl.content, COALESCE(tl.char_name,''),
		       w.title, e.short_code,
		       tl.act, tl.scene, tl.line_number
		FROM text_lines tl
		JOIN works w ON w.id = tl.work_id
		JOIN editions e ON e.id = tl.edition_id
		ORDER BY tl.id`)
	if err != nil {
		return err
	}
	defer rows.Close()

	log.Print("writing text_fts...")
	count := 0
	batch := newBatcher(w, "text_fts", "content", "char_name", "work_title", "work_slug", "edition_code", "act", "scene", "line_number")

	for rows.Next() {
		var (
			id                        int
			content, charName         string
			workTitle, editionCode    string
			act, scene, lineNumber    sql.NullInt64
		)
		if err := rows.Scan(&id, &content, &charName, &workTitle, &editionCode,
			&act, &scene, &lineNumber); err != nil {
			return err
		}

		batch.writeRow(id,
			sqlStr(content),
			sqlStr(charName),
			sqlStr(workTitle),
			sqlStr(slugify(workTitle)),
			sqlStr(editionCode),
			nullIntSQL(act),
			nullIntSQL(scene),
			nullIntSQL(lineNumber),
		)
		count++
	}
	batch.flush()

	if err := rows.Err(); err != nil {
		return err
	}
	log.Printf("  wrote %d text_fts rows", count)
	return nil
}

func writeLexiconFTS(w *bufio.Writer, src *sql.DB) error {
	rows, err := src.Query(`
		SELECT id, key, COALESCE(orthography,''), COALESCE(full_text,''), COALESCE(letter,'')
		FROM lexicon_entries
		ORDER BY id`)
	if err != nil {
		return err
	}
	defer rows.Close()

	log.Print("writing lexicon_fts...")
	count := 0
	batch := newBatcher(w, "lexicon_fts", "key", "orthography", "full_text", "letter")

	for rows.Next() {
		var id int
		var key, orthography, fullText, letter string
		if err := rows.Scan(&id, &key, &orthography, &fullText, &letter); err != nil {
			return err
		}
		batch.writeRow(id,
			sqlStr(key),
			sqlStr(orthography),
			sqlStr(fullText),
			sqlStr(letter),
		)
		count++
	}
	batch.flush()

	if err := rows.Err(); err != nil {
		return err
	}
	log.Printf("  wrote %d lexicon_fts rows", count)
	return nil
}

func writeReferenceFTS(w *bufio.Writer, src *sql.DB) error {
	rows, err := src.Query(`
		SELECT re.id, re.headword, COALESCE(re.raw_text,''), s.short_code, s.name
		FROM reference_entries re
		JOIN sources s ON s.id = re.source_id
		ORDER BY re.id`)
	if err != nil {
		return err
	}
	defer rows.Close()

	log.Print("writing reference_fts...")
	count := 0
	batch := newBatcher(w, "reference_fts", "headword", "raw_text", "source_code", "source_name")

	for rows.Next() {
		var id int
		var headword, rawText, sourceCode, sourceName string
		if err := rows.Scan(&id, &headword, &rawText, &sourceCode, &sourceName); err != nil {
			return err
		}
		batch.writeRow(id,
			sqlStr(headword),
			sqlStr(rawText),
			sqlStr(sourceCode),
			sqlStr(sourceName),
		)
		count++
	}
	batch.flush()

	if err := rows.Err(); err != nil {
		return err
	}
	log.Printf("  wrote %d reference_fts rows", count)
	return nil
}

// batcher writes INSERT statements for an FTS5 table.
type batcher struct {
	w       *bufio.Writer
	table   string
	colList string // comma-separated column names (excluding rowid)
	count   int
}

func newBatcher(w *bufio.Writer, table string, cols ...string) *batcher {
	return &batcher{w: w, table: table, colList: strings.Join(cols, ",")}
}

func (b *batcher) writeRow(id int, vals ...string) {
	fmt.Fprintf(b.w, "INSERT INTO %s(rowid,%s) VALUES(%d,%s);\n",
		b.table, b.colList, id, strings.Join(vals, ","))
	b.count++
}

func (b *batcher) flush() {}

// sqlStr returns a SQL string literal with single-quote escaping.
func sqlStr(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// nullIntSQL returns NULL or an integer literal for a NullInt64.
func nullIntSQL(n sql.NullInt64) string {
	if !n.Valid {
		return "NULL"
	}
	return fmt.Sprintf("%d", n.Int64)
}

// slugify converts a title like "Henry IV, Part I" to "henry-iv-part-i".
// Must stay in sync with the slugify function in internal/api/meta.go.
func slugify(title string) string {
	var b strings.Builder
	lastDash := true
	for _, r := range strings.ToLower(title) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			lastDash = false
		} else if !lastDash {
			b.WriteByte('-')
			lastDash = true
		}
	}
	return strings.TrimRight(b.String(), "-")
}

// ── reference_spans ──────────────────────────────────────────────────────────

type spanJSON struct {
	Start    int     `json:"start"`
	End      int     `json:"end"`
	WorkSlug *string `json:"work_slug,omitempty"`
	Act      *int    `json:"act,omitempty"`
	Scene    *int    `json:"scene,omitempty"`
	Line     *int    `json:"line,omitempty"`
}

type refCitJSON struct {
	WorkTitle *string `json:"work_title"`
	Act       *int    `json:"act"`
	Scene     *int    `json:"scene"`
	Line      *int    `json:"line"`
	WorkSlug  *string `json:"work_slug"`
}

func writeReferenceSpans(w *bufio.Writer, src *sql.DB) error {
	// Build citations map: entry_id → []refCitJSON
	citMap := map[int][]refCitJSON{}
	citRows, err := src.Query(`
		SELECT rc.entry_id, w.title, rc.act, rc.scene, rc.line
		FROM reference_citations rc
		LEFT JOIN works w ON w.id = rc.work_id
		ORDER BY rc.entry_id, w.title, rc.act, rc.scene, rc.line`)
	if err != nil {
		return fmt.Errorf("reference_citations: %w", err)
	}
	defer citRows.Close()
	for citRows.Next() {
		var entryID int
		var c refCitJSON
		if err := citRows.Scan(&entryID, &c.WorkTitle, &c.Act, &c.Scene, &c.Line); err != nil {
			return err
		}
		if c.WorkTitle != nil {
			s := slugify(*c.WorkTitle)
			c.WorkSlug = &s
		}
		citMap[entryID] = append(citMap[entryID], c)
	}
	if err := citRows.Err(); err != nil {
		return err
	}

	// Process entries
	rows, err := src.Query(`
		SELECT re.id, re.raw_text, s.short_code
		FROM reference_entries re
		JOIN sources s ON s.id = re.source_id
		ORDER BY re.id`)
	if err != nil {
		return err
	}
	defer rows.Close()

	log.Print("writing reference_spans...")
	count := 0
	for rows.Next() {
		var id int
		var rawText, sourceCode string
		if err := rows.Scan(&id, &rawText, &sourceCode); err != nil {
			return err
		}

		spans := parser.LocateCitationSpans(sourceCode, rawText)
		abbrevMap := abbrevMapForSource(sourceCode)
		spansList := make([]spanJSON, 0, len(spans))
		for _, sp := range spans {
			sj := spanJSON{Start: sp.Start, End: sp.End, Act: sp.Act, Scene: sp.Scene, Line: sp.Line}
			if slug := resolveAbbrevToSlug(sp.WorkAbbrev, abbrevMap); slug != "" {
				s := slug
				sj.WorkSlug = &s
			}
			spansList = append(spansList, sj)
		}
		sort.Slice(spansList, func(i, j int) bool { return spansList[i].Start < spansList[j].Start })

		spansBytes, _ := json.Marshal(spansList)

		cits := citMap[id]
		if cits == nil {
			cits = []refCitJSON{}
		}
		citsBytes, _ := json.Marshal(cits)

		fmt.Fprintf(w, "INSERT INTO reference_spans(id,citation_spans,citations) VALUES(%d,%s,%s);\n",
			id, sqlStr(string(spansBytes)), sqlStr(string(citsBytes)))
		count++
	}
	if err := rows.Err(); err != nil {
		return err
	}
	log.Printf("  wrote %d reference_spans rows", count)
	return nil
}

// abbrevMapForSource returns the source-specific abbreviation→Schmidt map.
func abbrevMapForSource(sourceCode string) map[string]string {
	switch sourceCode {
	case "abbott":
		return constants.AbbottAbbrevs
	case "onions":
		return constants.OnionsAbbrevs
	case "bartlett":
		return constants.BartlettAbbrevs
	case "henley_farmer":
		return constants.HenleyFarmerAbbrevs
	default:
		return nil
	}
}

// resolveAbbrevToSlug maps a source abbreviation to a work URL slug.
func resolveAbbrevToSlug(abbrev string, abbrevMap map[string]string) string {
	schmidtAbbrev := abbrev
	if abbrevMap != nil {
		if mapped, ok := abbrevMap[abbrev]; ok {
			schmidtAbbrev = mapped
		}
	}
	if work, ok := constants.SchmidtWorks[schmidtAbbrev]; ok {
		return slugify(work.Title)
	}
	return ""
}

// ── lexicon_drawer ────────────────────────────────────────────────────────────

type drawerSenseJSON struct {
	ID             int     `json:"id"`
	EntryID        int     `json:"entry_id"`
	SenseNumber    int     `json:"sense_number"`
	SubSense       *string `json:"sub_sense"`
	DefinitionText *string `json:"definition_text"`
}

type drawerSubEntryJSON struct {
	ID          int               `json:"id"`
	Key         string            `json:"key"`
	EntryType   *string           `json:"entry_type"`
	FullText    *string           `json:"full_text"`
	Orthography *string           `json:"orthography"`
	Senses      []drawerSenseJSON `json:"senses"`
	Citations   []struct{}        `json:"citations"`
}

// drawerRefJSON is intentionally minimal — one entry per reference_entry,
// no per-citation locations. The drawer links to /reference/[id] for details.
type drawerRefJSON struct {
	SourceName    string `json:"source_name"`
	SourceCode    string `json:"source_code"`
	EntryID       int    `json:"entry_id"`
	EntryHeadword string `json:"entry_headword"`
}

type lexiconDrawerJSON struct {
	ID          int                  `json:"id"`
	Key         string               `json:"key"`
	Orthography *string              `json:"orthography"`
	EntryType   *string              `json:"entry_type"`
	FullText    *string              `json:"full_text"`
	SubEntries  []drawerSubEntryJSON `json:"subEntries"`
	Senses      []drawerSenseJSON    `json:"senses"`
	Citations   []struct{}           `json:"citations"`
	References  []drawerRefJSON      `json:"references"`
}

func writeLexiconDrawer(w *bufio.Writer, src *sql.DB) error {
	// 1. Build senses map: entry_id → []drawerSenseJSON
	sensesMap := map[int][]drawerSenseJSON{}
	senseRows, err := src.Query(
		`SELECT id, entry_id, sense_number, sub_sense, definition_text
		 FROM lexicon_senses
		 ORDER BY entry_id, sense_number, COALESCE(sub_sense,'')`)
	if err != nil {
		return fmt.Errorf("lexicon_senses: %w", err)
	}
	defer senseRows.Close()
	for senseRows.Next() {
		var s drawerSenseJSON
		if err := senseRows.Scan(&s.ID, &s.EntryID, &s.SenseNumber, &s.SubSense, &s.DefinitionText); err != nil {
			return err
		}
		sensesMap[s.EntryID] = append(sensesMap[s.EntryID], s)
	}
	if err := senseRows.Err(); err != nil {
		return err
	}

	// 2. Build reference-entries map: LOWER(re.headword) → []drawerRefJSON
	// One row per reference_entry (not per citation) to keep JSON compact.
	refsMap := map[string][]drawerRefJSON{}
	refRows, err := src.Query(`
		SELECT LOWER(re.headword), src.name, src.short_code, re.id, re.headword
		FROM reference_entries re
		JOIN sources src ON src.id = re.source_id
		ORDER BY LOWER(re.headword), src.name, re.id`)
	if err != nil {
		return fmt.Errorf("reference_entries for drawer: %w", err)
	}
	defer refRows.Close()
	for refRows.Next() {
		var key string
		var r drawerRefJSON
		if err := refRows.Scan(&key, &r.SourceName, &r.SourceCode, &r.EntryID, &r.EntryHeadword); err != nil {
			return err
		}
		refsMap[key] = append(refsMap[key], r)
	}
	if err := refRows.Err(); err != nil {
		return err
	}

	// 3. Build entry groups: base_key → []entryInfo, ordered by sense_group, id
	type entryInfo struct {
		id          int
		key         string
		baseKey     string
		orthography *string
		entryType   *string
		fullText    *string
	}
	var allEntries []entryInfo
	entryRows, err := src.Query(
		`SELECT id, key, base_key, orthography, entry_type, full_text
		 FROM lexicon_entries
		 ORDER BY base_key, sense_group, id`)
	if err != nil {
		return fmt.Errorf("lexicon_entries: %w", err)
	}
	defer entryRows.Close()
	for entryRows.Next() {
		var e entryInfo
		if err := entryRows.Scan(&e.id, &e.key, &e.baseKey, &e.orthography, &e.entryType, &e.fullText); err != nil {
			return err
		}
		allEntries = append(allEntries, e)
	}
	if err := entryRows.Err(); err != nil {
		return err
	}

	// Group by base_key, preserving order
	type groupData struct {
		baseKey  string
		entries  []entryInfo
	}
	var groups []groupData
	groupIdx := map[string]int{}
	for _, e := range allEntries {
		if i, ok := groupIdx[e.baseKey]; ok {
			groups[i].entries = append(groups[i].entries, e)
		} else {
			groupIdx[e.baseKey] = len(groups)
			groups = append(groups, groupData{baseKey: e.baseKey, entries: []entryInfo{e}})
		}
	}

	log.Print("writing lexicon_drawer...")
	count := 0
	for _, g := range groups {
		subEntries := make([]drawerSubEntryJSON, len(g.entries))
		var allSenses []drawerSenseJSON
		for i, e := range g.entries {
			s := sensesMap[e.id]
			if s == nil {
				s = []drawerSenseJSON{}
			}
			allSenses = append(allSenses, s...)
			subEntries[i] = drawerSubEntryJSON{
				ID:          e.id,
				Key:         e.key,
				EntryType:   e.entryType,
				FullText:    e.fullText,
				Orthography: e.orthography,
				Senses:      s,
				Citations:   []struct{}{},
			}
		}
		if allSenses == nil {
			allSenses = []drawerSenseJSON{}
		}

		entryRefs := refsMap[strings.ToLower(g.baseKey)]
		if entryRefs == nil {
			entryRefs = []drawerRefJSON{}
		}

		primary := g.entries[0]
		drawer := lexiconDrawerJSON{
			ID:          primary.id,
			Key:         g.baseKey,
			Orthography: primary.orthography,
			EntryType:   primary.entryType,
			FullText:    primary.fullText,
			SubEntries:  subEntries,
			Senses:      allSenses,
			Citations:   []struct{}{},
			References:  entryRefs,
		}
		data, err := json.Marshal(drawer)
		if err != nil {
			return fmt.Errorf("marshal lexicon drawer %d: %w", primary.id, err)
		}
		// D1 max statement length is ~100KB. If the JSON is too large, trim
		// the References slice (which can be huge for common headwords like "Hen")
		// until the encoded INSERT fits. The full reference entry pages are
		// prerendered and accessible via /reference/[id].
		const maxJSON = 90_000
		for len(data) > maxJSON && len(drawer.References) > 0 {
			drawer.References = drawer.References[:len(drawer.References)/2]
			data, _ = json.Marshal(drawer)
		}

		// Store one row per entry ID in the group (same JSON, different rowid)
		for _, e := range g.entries {
			fmt.Fprintf(w, "INSERT INTO lexicon_drawer(id,data) VALUES(%d,%s);\n",
				e.id, sqlStr(string(data)))
			count++
		}
	}

	log.Printf("  wrote %d lexicon_drawer rows", count)
	return nil
}

func openReadOnly(path string) (*sql.DB, error) {
	db, err := sql.Open("sqlite", path+"?mode=ro")
	if err != nil {
		return nil, err
	}
	pragmas := []string{
		"PRAGMA journal_mode=WAL",
		"PRAGMA cache_size=-65536",
		"PRAGMA mmap_size=268435456",
	}
	for _, p := range pragmas {
		if _, err := db.Exec(p); err != nil {
			db.Close()
			return nil, fmt.Errorf("pragma %q: %w", p, err)
		}
	}
	return db, nil
}
